src/Raha/HomeBundle/Form/MembreType.php
<?php

namespace Raha\HomeBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MembreType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('etat')
            ->add('description')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Raha\HomeBundle\Entity\Membre'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'raha_homebundle_membre';
    }
}

src/Raha/HomeBundle/Controller/DefaultController.php
<?php

namespace Raha\HomeBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
// Import new namespaces
use Raha\HomeBundle\Entity\Enquiry;
use Raha\HomeBundle\Form\EnquiryType;
use Symfony\Component\HttpFoundation\Response;


class DefaultController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $repository = $em->getRepository('RahaHomeBundle:Article');
        $entities = $repository->createQueryBuilder('p')
        ->orderBy('p.date', 'DESC')
        ->getQuery()
        ->getResult();

        return $this->render('RahaHomeBundle:Default:index.html.twig', array(
            'entities' => $entities));
    }

    public function aboutAction()
    {
        return $this->render('RahaHomeBundle:Default:about.html.twig');
    }

	public function contactAction()
	{
	   $enquiry = new Enquiry();

    $form = $this->createForm(new EnquiryType(), $enquiry);

    $request = $this->getRequest();
    if ($request->getMethod() == 'POST') {
        $form->bindRequest($request);

        if ($form->isValid()) {
            // Perform some action, such as sending an email

            // Redirect - This is important to prevent users re-posting
            // the form if they refresh the page
            return $this->redirect($this->generateUrl('raha_contact'));
        }
    }

    return $this->render('RahaHomeBundle:Default:contact.html.twig', array(
        'form' => $form->createView()
    ));
	}
}

src/Raha/HomeBundle/Resources/views/Default/about.html.twig
{% extends '::base.html.twig' %}
{% block carousel %}
{% endblock %}
{% block title %}About{% endblock%}

{% block body %}
    <header>
        <h1>About TheRahaSite</h1>
    </header>
    <article>
        <p>Donec imperdiet ante sed diam consequat et dictum erat faucibus. Aliquam sit
        amet vehicula leo. Morbi urna dui, tempor ac posuere et, rutrum at dui.
        Curabitur neque quam, ultricies ut imperdiet id, ornare varius arcu. Ut congue
        urna sit amet tellus malesuada nec elementum risus molestie. Donec gravida
        tellus sed tortor adipiscing fringilla. Donec nulla mauris, mollis egestas
        condimentum laoreet, lacinia vel lorem. Morbi vitae justo sit amet felis
        vehicula commodo a placerat lacus. Mauris at est elit, nec vehicula urna. Duis a
        lacus nisl. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae.</p>
    </article>
{% endblock %}

src/Raha/HomeBundle/Resources/views/Default/contact.html.twig
{% extends '::base.html.twig' %}
{% block carousel %}
{% endblock %}
{% block title %}Contact{% endblock%}

{% block body %}
    <header>
        <h1>Contact TheRahaSite</h1>
    </header>
    <p>Voulez-vous nous contacter?</p>
     <form action="{{ path('raha_contact') }}" method="post" {{ form_enctype(form) }} class="Rahaform" role="form">

        {{ form_errors(form) }}
        
        {{ form_row(form.name, { 'label' : 'Nom'})}}
        {{ form_row(form.email, { 'label' : 'Email' }) }}
        {{ form_row(form.subject, { 'label' : 'Objet' }) }}
        {{ form_row(form.body, { 'label' : 'Votre Message' }) }}

        {{ form_rest(form) }}

        <input type="submit" value="Submit" />
    </form>
</form>
{% endblock %}

src/Raha/HomeBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}
{% block title %}Bienvenue sur {% endblock %}

{% block body %}
    {% for entity in entities %}
        <article class="blog">
            <div class="date"><time datetime="{{ entity.date|date('c') }}">{{ entity.date|date('l, F j, Y') }}</time></div>
            <header>
                <h2><a href="{{ path('article_show', { 'id': entity.id }) }}">{{ entity.titre }}</a></h2>
            </header>

            {% if entity.media %}
                {% thumbnail entity.media, 'small' %} {# render the related thumbnail #}
            {% endif %}
            <div class="snippet">
                <p>{{ entity.contenu(500) }}</p>
                <p class="continue"><a href="{{ path('article_show', { 'id': entity.id }) }}" class="btn btn-primary" role="button">Detail</a></p>
            </div>

            <footer class="meta">
                <p>Posted by <span class="highlight">{{entity.auteur}}</span> at {{ entity.date|date('h:iA') }}</p>
                <p>Tags: <span class="highlight">{{ entity.tags }}</span></p>
            </footer>
        </article>
    {% else %}
    {% if is_granted('ROLE_ADMIN') %}
    <ul class='admin_button'>
        <li>
            <a href="{{ path('article_new', { 'choice' : 'youtube'}) }}">
                new youtube
            </a>
        </li>
        <li>
            <a href="{{ path('article_new', { 'choice' : 'dailymotion'}) }}">
                new dailymotion
            </a>
        </li>
        <li>
            <a href="{{ path('article_new', { 'choice' : 'image'}) }}">
                new image
            </a>
        </li>
        <li>
            <a href="{{ path('article_new', { 'choice' : 'vimeo'}) }}">
                new vimeo
            </a>
        </li>
    </ul>
{% endif %}
        <p>Pas d'article trouve</p>
    {% endfor %}
{% endblock %}

src/Raha/HomeBundle/Resources/views/Default/layout.html.twig
{% extends '::base.html.twig' %}

{% block sidebar %}
    Sidebar content
{% endblock %}